more readable

diff --git a/webfinger b/webfinger
--- a/webfinger
+++ b/webfinger
@@ -22,9 +22,8 @@
 #       MA 02110-1301, USA.
 #
 
-ID=$1
-export WEBFINGERID=`echo -n acct:$ID | sed 's/:/%3a/g' | sed 's/@/%40/g'`
-HOSTMETA="`echo $ID | sed 's/^\(.*\)@\(.*\)/http:\/\/\2\/\.well-known\/host-meta/'`"
+export WEBFINGERID=`echo -n acct:$1 | sed 's/:/%3a/g' | sed 's/@/%40/g'`
+HOSTMETA="`echo $1 | sed 's/^\(.*\)@\(.*\)/http:\/\/\2\/\.well-known\/host-meta/'`"
 HOSTMETASSL="`echo "$HOSTMETA" | sed 's/^http/https/'`"
 (curl -s -L "$HOSTMETASSL" 2>/dev/null || curl -s -L "$HOSTMETA" 2>/dev/null) \
 	| awk '
@@ -32,16 +31,15 @@ HOSTMETASSL="`echo "$HOSTMETA" | sed 's/^http/https/'`"
 		RS = "<";
 		FS = ">";
 	}
-	tolower($1) ~ /^link.+rel[ \t\f\n\r\v]*=[ \t\f\n\r\v]*(\"lrdd\"|\'\''lrdd\'\''|lrdd)/ {
+	tolower($1) ~ /^link.+rel[ \t\f\n\r\v]*=[ \t\f\n\r\v]*(\"lrdd\"|\'"'"'lrdd\'"'"'|lrdd)/ {
 		template = $1;
-		addr = ENVIRON["WEBFINGERID"];
-		match(template, /template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*((\".*\"|\'\''.*\'\''))/);
+		match(template, /template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*((\".*\"|\'"'"'.*\'"'"'))/);
 		if(RLENGTH < 0) exit 1;
 		template = substr(template, RSTART, RLENGTH);
-		sub(/^template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*[\'\''\"]/, "", template);
-		sub(/[\'\''\"]$/, "", template);
-		gsub(/\{uri\}/, addr, template);
-		print template;
+		sub(/^template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*[\'"'"'\"]/, "", template);
+		sub(/[\'"'"'\"]$/, "", template);
+		gsub(/\{uri\}/, ENVIRON["WEBFINGERID"], template);
+		print "'"'"'" template "'"'"'";
 		exit 0;
 	}' \
-	| xargs curl -s -L 2>/dev/null || echo "Could not webfinger $ID" 1>&2
+	| xargs curl -s -L || echo "Could not webfinger $1" 1>&2
